kind: Service
apiVersion: v1
metadata:
  name: prototype-service
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    role: backend
    app: prototype
    env: dev
